/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shashanka and Sreedhar
 */

import Predictor.*;

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        output = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        GRE = new javax.swing.JLabel();
        GREexception = new javax.swing.JLabel();
        GREScore = new javax.swing.JTextField();
        GREline = new javax.swing.JSeparator();
        TOEFL = new javax.swing.JLabel();
        TOEFLexception = new javax.swing.JLabel();
        TOEFLScore = new javax.swing.JTextField();
        TOEFLline = new javax.swing.JSeparator();
        UNIVERSITY = new javax.swing.JLabel();
        RANKING = new javax.swing.JLabel();
        UNIRANKSlider = new javax.swing.JSlider();
        SOP = new javax.swing.JLabel();
        SOPSlider = new javax.swing.JSlider();
        LOR = new javax.swing.JLabel();
        LORSLIDER = new javax.swing.JSlider();
        CGPAlabel = new javax.swing.JLabel();
        CGPA = new javax.swing.JTextField();
        CGPAexception = new javax.swing.JLabel();
        CGPAline = new javax.swing.JSeparator();
        RESEARCH = new javax.swing.JLabel();
        EXPERIENCE = new javax.swing.JLabel();
        RESEXPexception = new javax.swing.JLabel();
        yesButton = new javax.swing.JRadioButton();
        noButton = new javax.swing.JRadioButton();
        generateResult = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        WindowAccent = new javax.swing.JPanel();
        informationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Information = new javax.swing.JTextArea();
        PredictorTEXT = new javax.swing.JTextField();
        Admission = new javax.swing.JTextField();
        College = new javax.swing.JTextField();
        Close = new javax.swing.JButton();

        output.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 40)); // NOI18N
        output.setForeground(new java.awt.Color(0, 200, 170));
        output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(10, 61, 98));
        mainPanel.setPreferredSize(new java.awt.Dimension(2100, 950));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRE.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        GRE.setForeground(new java.awt.Color(0, 204, 153));
        GRE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        GRE.setText("GRE SCORE");
        mainPanel.add(GRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 140, 50));

        GREexception.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GREexception.setForeground(new java.awt.Color(204, 0, 0));
        mainPanel.add(GREexception, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 540, 30));

        GREScore.setBackground(new java.awt.Color(0, 25, 50));
        GREScore.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        GREScore.setForeground(new java.awt.Color(255, 255, 255));
        GREScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GREScore.setBorder(null);
        GREScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GREScoreActionPerformed(evt);
            }
        });
        mainPanel.add(GREScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 380, 30));
        mainPanel.add(GREline, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 380, 10));

        TOEFL.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        TOEFL.setForeground(new java.awt.Color(0, 204, 153));
        TOEFL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TOEFL.setText("TOEFL SCORE");
        mainPanel.add(TOEFL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        TOEFLexception.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TOEFLexception.setForeground(new java.awt.Color(204, 0, 0));
        mainPanel.add(TOEFLexception, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 540, 30));

        TOEFLScore.setBackground(new java.awt.Color(0, 25, 50));
        TOEFLScore.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        TOEFLScore.setForeground(new java.awt.Color(255, 255, 255));
        TOEFLScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TOEFLScore.setBorder(null);
        TOEFLScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOEFLScoreActionPerformed(evt);
            }
        });
        mainPanel.add(TOEFLScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 380, 30));
        mainPanel.add(TOEFLline, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 380, 10));

        UNIVERSITY.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        UNIVERSITY.setForeground(new java.awt.Color(0, 204, 153));
        UNIVERSITY.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UNIVERSITY.setText("UNIVERSITY ");
        UNIVERSITY.setToolTipText("");
        mainPanel.add(UNIVERSITY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));

        RANKING.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        RANKING.setForeground(new java.awt.Color(0, 204, 153));
        RANKING.setText("RANKING");
        mainPanel.add(RANKING, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, -1));

        UNIRANKSlider.setForeground(new java.awt.Color(50, 255, 255));
        UNIRANKSlider.setMajorTickSpacing(1);
        UNIRANKSlider.setMaximum(5);
        UNIRANKSlider.setMinimum(1);
        UNIRANKSlider.setPaintLabels(true);
        UNIRANKSlider.setPaintTicks(true);
        UNIRANKSlider.setSnapToTicks(true);
        UNIRANKSlider.setValue(3);
        mainPanel.add(UNIRANKSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 380, 50));

        SOP.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        SOP.setForeground(new java.awt.Color(0, 204, 153));
        SOP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SOP.setText("SOP");
        mainPanel.add(SOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        SOPSlider.setForeground(new java.awt.Color(51, 255, 255));
        SOPSlider.setMajorTickSpacing(1);
        SOPSlider.setMaximum(5);
        SOPSlider.setMinimum(1);
        SOPSlider.setPaintLabels(true);
        SOPSlider.setPaintTicks(true);
        SOPSlider.setSnapToTicks(true);
        SOPSlider.setToolTipText("");
        SOPSlider.setValue(3);
        mainPanel.add(SOPSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 380, 50));

        LOR.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        LOR.setForeground(new java.awt.Color(0, 204, 153));
        LOR.setText("LOR");
        mainPanel.add(LOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        LORSLIDER.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 13)); // NOI18N
        LORSLIDER.setForeground(new java.awt.Color(51, 255, 255));
        LORSLIDER.setMajorTickSpacing(1);
        LORSLIDER.setMaximum(5);
        LORSLIDER.setMinimum(1);
        LORSLIDER.setPaintLabels(true);
        LORSLIDER.setPaintTicks(true);
        LORSLIDER.setSnapToTicks(true);
        LORSLIDER.setToolTipText("Enter");
        LORSLIDER.setValue(3);
        LORSLIDER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.add(LORSLIDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 380, 50));

        CGPAlabel.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        CGPAlabel.setForeground(new java.awt.Color(0, 204, 153));
        CGPAlabel.setText("CGPA");
        mainPanel.add(CGPAlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        CGPA.setBackground(new java.awt.Color(0, 25, 50));
        CGPA.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        CGPA.setForeground(new java.awt.Color(255, 255, 255));
        CGPA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CGPA.setBorder(null);
        CGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGPAActionPerformed(evt);
            }
        });
        mainPanel.add(CGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 380, 30));

        CGPAexception.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CGPAexception.setForeground(new java.awt.Color(204, 0, 0));
        mainPanel.add(CGPAexception, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 410, 540, 30));
        mainPanel.add(CGPAline, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 380, 20));

        RESEARCH.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        RESEARCH.setForeground(new java.awt.Color(0, 204, 153));
        RESEARCH.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RESEARCH.setText("RESEARCH");
        mainPanel.add(RESEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        EXPERIENCE.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        EXPERIENCE.setForeground(new java.awt.Color(0, 204, 154));
        EXPERIENCE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EXPERIENCE.setText("EXPERIENCE");
        mainPanel.add(EXPERIENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        RESEXPexception.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RESEXPexception.setForeground(new java.awt.Color(204, 0, 0));
        mainPanel.add(RESEXPexception, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 280, 20));

        yesButton.setBackground(new java.awt.Color(255, 255, 255));
        yesButton.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        yesButton.setForeground(new java.awt.Color(0, 102, 255));
        yesButton.setText("YES");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });
        mainPanel.add(yesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, 30));

        noButton.setBackground(new java.awt.Color(255, 255, 255));
        noButton.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        noButton.setForeground(new java.awt.Color(0, 102, 255));
        noButton.setText("NO");
        noButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 70, 30));

        generateResult.setBackground(new java.awt.Color(0, 25, 50));
        generateResult.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        generateResult.setForeground(new java.awt.Color(0, 204, 154));
        generateResult.setText("GENERATE RESULT");
        generateResult.setBorder(null);
        generateResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateResultActionPerformed(evt);
            }
        });
        mainPanel.add(generateResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 560, 60));

        Result.setBackground(new java.awt.Color(0, 204, 153));
        Result.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 20)); // NOI18N
        Result.setForeground(new java.awt.Color(0, 204, 153));
        Result.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainPanel.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 550, 70));

        jPanel1.setBackground(new java.awt.Color(29, 29, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 20, 690));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 610, 680));

        WindowAccent.setBackground(new java.awt.Color(61, 61, 61));

        javax.swing.GroupLayout WindowAccentLayout = new javax.swing.GroupLayout(WindowAccent);
        WindowAccent.setLayout(WindowAccentLayout);
        WindowAccentLayout.setHorizontalGroup(
            WindowAccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        WindowAccentLayout.setVerticalGroup(
            WindowAccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(WindowAccent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        informationPanel.setBackground(new java.awt.Color(36, 117, 176));
        informationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Information.setEditable(false);
        Information.setBackground(new java.awt.Color(25, 42, 86));
        Information.setColumns(20);
        Information.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        Information.setForeground(new java.awt.Color(255, 255, 255));
        Information.setLineWrap(true);
        Information.setRows(5);
        Information.setText("  \n     THIS IS A SIMPLE-TO-USE TOOL\n     WHICH TAKES IN YOUR ACADEMIC\n     CREDENTIALS AND COMPUTES\n     YOUR CHANCES OF MAKING IT\n     TO A UNIVERSITY IN THE US FOR\n     A POST-GRADUATE DEGREE.\n\n     THIS IS CREATED BY BUILDING\n     A LINEAR REGRESSION MODEL\n     FROM A LARGE DATASET OF \n     HUNDREDS OF INDIAN STUDENTS,\n     WHO HAVE ATTEMPTED TO DO\n     THEIR PG IN THE US.");
        Information.setWrapStyleWord(true);
        Information.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 25, 50)));
        jScrollPane1.setViewportView(Information);

        informationPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 340));

        PredictorTEXT.setEditable(false);
        PredictorTEXT.setBackground(new java.awt.Color(36, 117, 176));
        PredictorTEXT.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 54)); // NOI18N
        PredictorTEXT.setForeground(new java.awt.Color(24, 222, 136));
        PredictorTEXT.setText("PREDICTOR");
        PredictorTEXT.setBorder(null);
        informationPanel.add(PredictorTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 50));

        Admission.setBackground(new java.awt.Color(36, 117, 176));
        Admission.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 52)); // NOI18N
        Admission.setForeground(new java.awt.Color(24, 231, 137));
        Admission.setText("ADMISSION");
        Admission.setBorder(null);
        Admission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmissionActionPerformed(evt);
            }
        });
        informationPanel.add(Admission, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 40));

        College.setBackground(new java.awt.Color(36, 117, 176));
        College.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 70)); // NOI18N
        College.setForeground(new java.awt.Color(24, 231, 137));
        College.setText("COLLEGE");
        College.setBorder(null);
        College.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollegeActionPerformed(evt);
            }
        });
        informationPanel.add(College, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 70));

        getContentPane().add(informationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 380, 690));

        Close.setBackground(new java.awt.Color(61, 61, 61));
        Close.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Close.setText("X");
        Close.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 47, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateResultActionPerformed
        // TODO add your handling code here:
 
        class GREException extends Exception {
            GREException() { }
            @Override
            public String toString() {
                return("Please enter a value between 0 and 340");
            }
        }

        class TOEFLException extends Exception {
            TOEFLException() { }
            @Override
            public String toString() {
                return("Please enter a value between 0 and 120");
            }
        }

        class CGPAException extends Exception {
            CGPAException() { }
            @Override
            public String toString() {
                return("Please enter a value between 0 and 10");
            }
        }

        class RESEXPException extends Exception {
            RESEXPException() { }
            @Override
            public String toString() {
                return("Please choose either Yes or No");
            }
        }
        GREexception.setText("");
        TOEFLexception.setText("");
        CGPAexception.setText("");
        RESEXPexception.setText("");
        Result.setText("");
        int flag1=0,flag2=0,flag3=0;
        double arr[] = new double[8];
        arr[0]=(double)1;
        try{
            arr[1]=Double.parseDouble(GREScore.getText());
            if(arr[1]<0 || arr[1]>340)
            {  
                flag1=1;
                throw new GREException();
            }    
        }
        catch(Exception e)
        {
            GREexception.setText(""+e);
        }    
        try{
               arr[2]=Double.parseDouble(TOEFLScore.getText());
               if(arr[2]<0 || arr[2]>120)
               {
                   flag2=1;
                   throw new TOEFLException();
               }
                   
        }
        catch(Exception e)
        {
            TOEFLexception.setText(""+e);
        }
     
        arr[3]=UNIRANKSlider.getValue();
        arr[4]=SOPSlider.getValue();
        arr[5]=LORSLIDER.getValue();
        try{
            arr[6]=Double.parseDouble(CGPA.getText());
            if(arr[6]<0 || arr[6]>10)
            {
                flag3=1;
                throw new CGPAException();
            }    
        }
        catch(Exception e)
        {
            CGPAexception.setText(""+e);
        }
        if(yesButton.isSelected() && noButton.isSelected())
            RESEXPexception.setText("Please choose either Yes or NO");        
        else if(yesButton.isSelected())
            arr[7]=(double)1;
        else if(noButton.isSelected())
            arr[7]=(double)0;
        else
            RESEXPexception.setText("Please choose either Yes or No");
        
        if(flag1==0 && flag2==0 && flag3==0)
        {
            int predd = (int)(Predictor.pred(arr)*100);
            if(predd<0)
                predd = 0;
            if(predd>100)
                predd=100;
            Result.setText("YOUR CHANCE OF ADMISSION IS:  " + predd + "%");
        //  page3 p3 = new page3();
        // p3.setVisible(true);
        // this.dispose();
        }

    }//GEN-LAST:event_generateResultActionPerformed

    private void CGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGPAActionPerformed

    private void TOEFLScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOEFLScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOEFLScoreActionPerformed

    private void GREScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GREScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GREScoreActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesButtonActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    private void CollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CollegeActionPerformed

    private void AdmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmissionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admission;
    private javax.swing.JTextField CGPA;
    private javax.swing.JLabel CGPAexception;
    private javax.swing.JLabel CGPAlabel;
    private javax.swing.JSeparator CGPAline;
    private javax.swing.JButton Close;
    private javax.swing.JTextField College;
    private javax.swing.JLabel EXPERIENCE;
    private javax.swing.JLabel GRE;
    private javax.swing.JTextField GREScore;
    private javax.swing.JLabel GREexception;
    private javax.swing.JSeparator GREline;
    private javax.swing.JTextArea Information;
    private javax.swing.JLabel LOR;
    private javax.swing.JSlider LORSLIDER;
    private javax.swing.JTextField PredictorTEXT;
    private javax.swing.JLabel RANKING;
    private javax.swing.JLabel RESEARCH;
    private javax.swing.JLabel RESEXPexception;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel SOP;
    private javax.swing.JSlider SOPSlider;
    private javax.swing.JLabel TOEFL;
    private javax.swing.JTextField TOEFLScore;
    private javax.swing.JLabel TOEFLexception;
    private javax.swing.JSeparator TOEFLline;
    private javax.swing.JSlider UNIRANKSlider;
    private javax.swing.JLabel UNIVERSITY;
    private javax.swing.JPanel WindowAccent;
    private javax.swing.JButton generateResult;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton noButton;
    private javax.swing.JLabel output;
    private javax.swing.JRadioButton yesButton;
    // End of variables declaration//GEN-END:variables
}
